version: '3.9'
services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=some
      - POSTGRES_PASSWORD=some
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

